meetupfinder/urls.py
from django.urls import path
from . import views

app_name = 'meetupfinder'

urlpatterns = [
    path('', views.index, name='index'),
    path('events/', views.events, name='events'),
    path('profile/', views.profile, name='profile'),
    path('attend/<int:event_id>/', views.attend, name='attend'),
    path('cancel_attendance/<int:event_id>/', views.cancel_attendance, name='cancel_attendance'),
    path('add_event/', views.add_event, name='add_event')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="meetupfinder/index.html")), # <--
    path('meetupfinder/', include('meetupfinder.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

meetupfinder/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django_google_maps import fields as map_fields
from places.fields import PlacesField

# Create your models here.
# categories (own model)
class Categories(models.Model):
    cat_name= models.CharField(max_length=200)
    def __str__(self):
       return self.cat_name

class Event(models.Model):
    event_name= models.CharField(max_length=200)
    event_text= models.CharField(max_length=400)
    event_host= models.CharField(max_length=200)
    event_date= models.DateTimeField('event date', null=True, blank=True)
    end_event_date= models.DateTimeField('end event date', null=True, blank=True)
    category = models.ForeignKey(Categories, null=True, blank=True, on_delete=models.CASCADE)
    attending_users = models.ManyToManyField(User, related_name='attending_events', blank=True)
    #locate = PlacesField(null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    latitude = models.DecimalField(null=True, blank=True, decimal_places=3, max_digits=10)
    longitude = models.DecimalField(null=True, blank=True, decimal_places=3, max_digits=10)
    def __str__(self):
       return self.event_text
# location -- text field or something else

meetupfinder/forms.py
from django import forms
from .models import Categories
from django.core.exceptions import ValidationError

class EventFilterForm(forms.Form):
    name = forms.CharField(label='Event Name', max_length=200, required=False,
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'}))
    
    start_date = forms.DateField(label='Start Date', required=False, input_formats={'%m/%d/%y'},
        widget=forms.DateInput(attrs={'class': 'form-control form-control-sm', 'placeholder': 'MM/DD/YY'}))

    end_date = forms.DateField(label='End Date', required=False, input_formats={'%m/%d/%y'},
        widget=forms.DateInput(attrs={'class': 'form-control form-control-sm', 'placeholder': 'MM/DD/YY'}))
        
    category = forms.ModelMultipleChoiceField(label="Categories (SHIFT-Click for multiple)", required=False,
        queryset=Categories.objects.all(), widget=forms.SelectMultiple(attrs={'class': 'form-control form-control-sm'}))

    location = forms.CharField(label='My Address', max_length=200, required=False,
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'}))
    
    distance = forms.IntegerField(label='Filtering Range (miles)', required=False,
        widget = forms.NumberInput(attrs={'min': '10', 'class': 'form-control form-control-sm',
        'placeholder': 'Requires address'}))

    #if one of distance or location provided, other must also be provided
    def clean(self):
        cleaned_data = super().clean()
        location = cleaned_data.get("location")
        distance = cleaned_data.get("distance")
        if location is not "" or distance is not None:
            if location is "":
                self.add_error('location', 
                    ValidationError("Please provide a starting address along with the filtering range."))
            if distance is None:
                self.add_error('distance', 
                    ValidationError("Please provide a filtering range along with the starting address."))



class AddEventForm(forms.Form):
    name = forms.CharField(label='Event Name', max_length=200,
        widget=forms.TextInput(attrs={'class': 'form-control'}))

    description = forms.CharField(label='Description', max_length=400,
        widget=forms.Textarea(attrs={'class': 'form-control'}))
    
    host = forms.CharField(label='Event Host', max_length=200,
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    
    date = forms.DateField(label='Date', input_formats={'%m/%d/%y'},
        widget=forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'MM/DD/YY'}))

    start_time = forms.TimeField(label='Start Time', input_formats={'%I:%M %p'},
        widget=forms.TimeInput(attrs={'class': 'form-control', 'placeholder': '10:15 AM'}))
    
    end_time = forms.TimeField(label="End Time", input_formats={'%I:%M %p'},
        widget=forms.TimeInput(attrs={'class': 'form-control', 'placeholder': '2:15 PM'}))
    
    address = forms.CharField(label='Address', max_length=200,
        widget=forms.TextInput(attrs={'class': 'form-control',
        'placeholder': '1600 Amphitheatre Parkway, Mountain View, CA'}))
        
    category = forms.ModelChoiceField(label="Category", queryset=Categories.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}))

meetupfinder/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, resolve
from django.http import HttpResponse, HttpResponseRedirect
from .models import Event
from .forms import EventFilterForm, AddEventForm
from datetime import datetime
from places.fields import PlacesField
from json import dumps
import requests, math, decimal


def index(request):
    return render(request, 'meetupfinder/index.html')

def profile(request):
    attending_events = request.user.attending_events.all()
    return render(request, 'meetupfinder/profile.html', {'attending_events': attending_events})
    
def events(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('meetupfinder:index'))
    
    events = Event.objects.order_by('-event_date')
    
    #if form submission, validate data and filter
    if request.method == 'POST':
        form = EventFilterForm(request.POST)
        if form.is_valid():
            #filter by name if provided
            name = form.cleaned_data['name']
            if name is not "":
                events = events.filter(event_name__icontains=name)
            #filter by start date if provided
            start_date = form.cleaned_data['start_date']
            if start_date is not None:
                events = events.filter(event_date__date__gte=start_date)
            #filter by end date if provided
            end_date = form.cleaned_data['end_date']
            if end_date is not None:
                events = events.filter(end_event_date__date__lte=end_date)
            #filter by categories if provided
            categoriesList = form.cleaned_data['category']
            if categoriesList:
                events = events.filter(category__id__in=categoriesList)
            #filter by distance range if range and user location provided
            location = form.cleaned_data['location']
            form_range = form.cleaned_data['distance']
            if location is not "" and form_range is not None:
                api_key = "AIzaSyCf4vECJyy-z-pq7NV93fpwP5hlZYs8pmo"
                r = requests.get(f"https://maps.googleapis.com/maps/api/geocode/json?address={location}&key={api_key}")
                user_lat = r.json()["results"][0]["geometry"]["location"]["lat"]
                user_lon = r.json()["results"][0]["geometry"]["location"]["lng"]
                # if an event is farther away from the user than the specified range, remove it from results
                for event in events:
                    if calculateDistance(event.latitude, event.longitude, user_lat, user_lon) > form_range:
                        events = events.exclude(id=event.id)
    
    #otherwise, create blank form
    else:
        form = EventFilterForm()
        
    #create location information for map
    locations = []
    for event in events:
        locations.append([event.event_name, event.address, float(event.latitude), float(event.longitude)])
    locationData = dumps({'locations': locations})
    
    return render(request, 'meetupfinder/events.html', {'title': 'Events', 'events': events, 
    'locationData': locationData, 'form': form})


#helper function to find distance (in miles) between two lat-long points using Law of Cosines
def calculateDistance(lat1, lng1, lat2, lng2):
	φ1 = decimal.Decimal(lat1) * decimal.Decimal(math.pi/180)
	φ2 = decimal.Decimal(lat2) * decimal.Decimal(math.pi/180)
	Δλ = (decimal.Decimal(lng2)-decimal.Decimal(lng1)) * decimal.Decimal(math.pi/180)
	R = 6371
	dKm = math.acos( math.sin(φ1)*math.sin(φ2) + math.cos(φ1)*math.cos(φ2) * math.cos(Δλ) ) * R
	distMI = dKm * 0.621371 #km to miles
	return distMI


def attend(request, event_id):
    if request.method == 'POST' and request.user.is_authenticated:
        event = get_object_or_404(Event, pk=event_id)
        event.attending_users.add(request.user)
        event.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        return HttpResponseRedirect(reverse('meetupfinder:index'))


def cancel_attendance(request, event_id):
    if request.method == 'POST' and request.user.is_authenticated:
        event = get_object_or_404(Event, pk=event_id)
        event.attending_users.remove(request.user)
        event.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        return HttpResponseRedirect(reverse('meetupfinder:index'))


def add_event(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('meetupfinder:index'))
    
    #if form submission, validate data and filter
    if request.method == 'POST':
        form = AddEventForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            description = form.cleaned_data['description']
            host = form.cleaned_data['host']
            date = form.cleaned_data['date']
            start_time = form.cleaned_data['start_time']
            end_time = form.cleaned_data['end_time']
            category = form.cleaned_data['category']
            address = form.cleaned_data['address']

            #process the date and time info
            start_date = datetime(date.year, date.month, date.day, 
                start_time.hour, start_time.minute)
            end_date = datetime(date.year, date.month, date.day,
                end_time.hour, end_time.minute)
            
            #process address data with Google Maps Geocoding API
            api_key = "AIzaSyCf4vECJyy-z-pq7NV93fpwP5hlZYs8pmo"
            r = requests.get(f"https://maps.googleapis.com/maps/api/geocode/json?address={address}&key={api_key}")
            latitude = r.json()["results"][0]["geometry"]["location"]["lat"]
            longitude = r.json()["results"][0]["geometry"]["location"]["lng"]

            #create and save the new event to the database
            event = Event(event_name=name, event_text=description, event_host=host, event_date=start_date,
            end_event_date=end_date, category=category, address=address, latitude=latitude, longitude=longitude)
            event.save()
            return HttpResponseRedirect(reverse('meetupfinder:events'))
        
    #otherwise, create blank form
    else:
        form = AddEventForm()
    
    return render(request, 'meetupfinder/add_event.html', {'title': 'Add Event', 'form': form})

meetupfinder/templates/meetupfinder/add_event.html
{% extends 'meetupfinder/base.html' %}

{% block content %}

    <h3>Add Event</h3>
    <br>

    <div class="col-md-4">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <p class="alert alert-danger">{{ field.label }}: {{ error }}</p>
                {% endfor %}
            {% endfor %}
        {% endif %}

        <form action="{% url 'meetupfinder:add_event' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.name.label }}
                {{ form.name }}
            </div>
            <div class="form-group">
                {{ form.description.label }}
                {{ form.description }}
            </div>
            <div class="form-group">
                {{ form.host.label }}
                {{ form.host }}
            </div>
            <div class="form-group">
                {{ form.date.label }}
                {{ form.date }}
            </div>
            <div class="form-group">
                {{ form.start_time.label }}
                {{ form.start_time }}
            </div>
            <div class="form-group">
                {{ form.end_time.label }}
                {{ form.end_time }}
            </div>
            <div class="form-group">
                {{ form.category.label }}
                {{ form.category }}
            </div>
            <div class="form-group">
                {{ form.address.label }}
                {{ form.address }}
            </div>

            <input type="submit" class="btn btn-primary" value="Create"/>
        </form>
    </div>
    <br><br>

{% endblock %}

meetupfinder/templates/meetupfinder/base.html
<!DOCTYPE html>
{% load socialaccount %}
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
		    <title>Meet-Up Finder – {{ title }}</title>
	    {% else %}
		    <title>Meet-Up Finder</title>
	    {% endif %}

        <!--Bootstrap CSS from CDN -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 
    </head>
    
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'meetupfinder:index' %}">Meet-Up Finder</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse ml-3" id="navbarNavAltMarkup">
              <!-- navbar left -->
              <div class="navbar-nav">
                <a class="nav-item nav-link mr-3" href="{% url 'meetupfinder:events' %}">Find Events</a>
                <a class="nav-item nav-link mr-3" href="{% url 'meetupfinder:add_event' %}">Add Event</a>
                {% if user.is_authenticated %}
                <a class="nav-item nav-link mr-3" href="{% url 'meetupfinder:profile' %}">Profile</a>
                {% endif %}
              </div>
              <!-- navbar right -->
              <div class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <form method="post" action="{% url 'account_logout' %}">
                  {% csrf_token %}
                  {% if redirect_field_value %}
                  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                  {% endif %}
                  <button class="btn btn-link nav-item nav-link" type="submit">Sign Out</button>
                </form>

                {% else %}
                <a class="nav-item nav-link" href="{% provider_login_url 'google' %}">Login with Google</a>
                {% endif %}
              </div>
            </div>
        </nav>

        <div class="p-4" width="100%">
          
          {% block content %}
          {% endblock %}
            
        </div>
        
        <!-- Bootstrap JS from CDN -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>


{% block styles %}
{% endblock %}

meetupfinder/templates/meetupfinder/event.html
<div class="card shadow mt-3 mb-3 ml-4" style="border: none">
  <p class="card-header" style="background-color: #23395d; margin-bottom: 0px">
      <a style="color: white">{{ event.event_name }} –
          <span style="opacity: 75%">{{ event.category }}</span>
          {% if event in user.attending_events.all %}
              <span class="badge badge-pill badge-success ml-3" style="font-size: 0.875rem;
              float: right">Attending</span>
          {% endif %}
      </a>
  </p>
  
  <div class="card-body">
      <div style="float: left; width: 70%">
          <p style="margin-bottom: 0px"><strong>{{ event.event_date|date:'l, m/d/Y'}}</strong></p>
          <p class="text-muted"> {{ event.event_date|date:'g:i A' }} – 
              {{ event.end_event_date|date:'g:i A' }}
          </p>
          <p id="address" name="{{ event.latitude }}" value="{{ event.longitude }}">{{ event.address }}</p>
          <p>Host: {{ event.event_host }}</p>
          <p> {{ event.event_text }}</p>
      </div>
      
      <div style="float: right; padding-top: 5px; margin-left: 3px">
          {% if event in user.attending_events.all %}
          <form method="post" action="{% url 'meetupfinder:cancel_attendance' event.id %}">
              {% csrf_token %}
              <input type="submit" class="btn btn-sm btn-danger" value="Cancel">
          </form>
          {% else %}
          <form method="post" action="{% url 'meetupfinder:attend' event.id %}">
              {% csrf_token %}
              <input type="submit" class="btn btn-sm btn-success" value="Attend">
          </form>
          {% endif %}
      </div>
  </div>
</div>

meetupfinder/templates/meetupfinder/events.html
{% extends 'meetupfinder/base.html' %}

{% block content %}

    <h3>Events</h3>

    <div class="mt-3 p-3 mb-3 shadow-sm card" style="float: left; width: 20%; min-height: 625px">
        <h5 class="mb-3">Filter Results</h5>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <small class="alert alert-danger">{{ field.label }}: {{ error }}</small>
                {% endfor %}
            {% endfor %}
        {% endif %}
        <form action="{% url 'meetupfinder:events' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.name.label }}
                {{ form.name }}
            </div>
            <div class="form-group">
                {{ form.start_date.label }}
                {{ form.start_date }}
            </div>
            <div class="form-group">
                {{ form.end_date.label }}
                {{ form.end_date }}
            </div>
            <div class="form-group">
                {{ form.category.label }}
                {{ form.category }}
            </div>
            <div class="form-group">
                {{ form.location.label }}
                {{ form.location }}
            </div>
            <div class="form-group">
                {{ form.distance.label }}
                {{ form.distance }}
            </div>

            <input type="submit" class="btn btn-sm btn-primary" value="Filter"/>
        </form>
    </div>

    <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCf4vECJyy-z-pq7NV93fpwP5hlZYs8pmo&callback=initMap&libraries=&v=weekly"
    defer></script>

    <script>
        // Initialize and add the map
        function initMap() {
          var infowindow = new google.maps.InfoWindow({})
          var marker, count;
          
          var locationData = JSON.parse("{{locationData|escapejs}}");
          var locations = locationData['locations']

          const map = new google.maps.Map(document.getElementById("map"), {
            zoom: 3,
            center: {'lat': 41.850033, 'lng': -87.6500523},
          });

          for(count = 0; count < locations.length; count++){
              marker = new google.maps.Marker({
                  position: {lat: parseFloat(locations[count][2]), lng: parseFloat(locations[count][3])},
                  map: map,
                  title: locations[count][0]
              });
              google.maps.event.addListener(marker, 'click', (function(marker, count){
                return function(){
                    infowindow.setContent("" + locations[count][0] + ': ' + locations[count][1]);
                    infowindow.open(map, marker);
                }
              })(marker, count));
          }
        }
    </script>
    <div id="map" class="ml-4 mt-3" style="float: left"></div>

    <div class="mt-3 mb-5" style="float: left; height: 625px; width: 38%">
        <h5 class="ml-4" id="locations" value="{{ locations }}">Results</h5>
        <div style="overflow-y: scroll; height: 595px">
        {% for event in events %}
            {% include 'meetupfinder/event.html' %}
        {% endfor %}
        </div>
    </div>

{% endblock %}

{% block styles %}
<style type="text/css">
    /* Set the size of the div element that contains the map */
    #map {
      height: 625px;
      width: 40%;
    }
</style>
{% endblock %}

meetupfinder/templates/meetupfinder/index.html
{% extends 'meetupfinder/base.html' %}
{% load socialaccount %}

{% block content %}
  {% if user.is_authenticated %}
    <h3>Welcome, {{ user.username | title }}!</h3>
    <div class="row" style="justify-content: center">
      <div class="card shadow-sm col-md-3 m-3 info-card">
        <a href="{% url 'meetupfinder:events' %}" style="text-decoration: none; color: inherit">
        <div class="card-body">
          <h5 class="card-title">Find Events</h5>
          <p class="card-text">View all of the events stored in the Meet-Up Finder system, and filter them based on
            your criteria to find events you'd like to attend.</p>
        </div>
        </a>
      </div>
      <div class="card shadow-sm col-md-3 m-3 info-card">
        <a href="{% url 'meetupfinder:add_event' %}" style="text-decoration: none; color: inherit">
        <div class="card-body">
          <h5 class="card-title">Add Event</h5>
          <p class="card-text">Add a new event to the system to publicize it to all Meet-Up Finder users and
            boost attendance at your event.</p>
        </div>
        </a>
      </div>
      <div class="card shadow-sm col-md-3 m-3 info-card">
        <a href="{% url 'meetupfinder:profile' %}" style="text-decoration: none; color: inherit">
        <div class="card-body">
          <h5 class="card-title">View Profile</h5>
          <p class="card-text">Visit your profile to see details about your account and view a list of all
          upcoming events you're scheduled to attend.</p>
        </div>
        </a>
      </div>
    </div>
  
  {% else %}
    <div class="shadow-sm p-4 text-center mr-auto ml-auto mt-5" style="width: 50%; border: 1px solid rgba(0,0,0,.125)">
      <h3 class="mb-4">Please sign in to see content.</h3>
      <a href="{% provider_login_url 'google' %}" class="btn btn-primary">Login with Google</a>
    </div>
  {% endif %}
  
{% endblock %}


{% block styles %}
<style>
    div.info-card:hover {
      box-shadow: 0 .5rem 1rem rgba(0,0,0,.1)!important;
    }
</style>
{% endblock %}

meetupfinder/templates/meetupfinder/profile.html
{% extends 'meetupfinder/base.html' %}

{% block content %}
  <h3>This is {{ user.username | title }}'s profile!</h3>
  <p>Date Joined: {{ user.date_joined }}</p>
  <p>Last Login: {{ user.last_login }}</p>

  <h5 class="mt-4">My Upcoming Events</h5>
  <div class="col-md-6">
    {% for event in attending_events %}
      {% include 'meetupfinder/event.html' %}
    {% endfor %}
  </div>

{% endblock %}